[package]
name = "file-sorter"
version = "1.1.2"
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
walkdir = "2.3.1"
