[package]
name = "file-sorter"
version = "1.1.8"
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
rand = "0.8.1"
walkdir = "2.3.1"
