[package]
name = "file-sorter"
version = "1.1.19"
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
clap = "3.0.0-beta.5"
rand = "0.8.4"
walkdir = "2.3.2"
