[package]
name = "file-sorter"
version = "1.1.22"
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
chrono = "0.4.19"
clap = { version = "3.0.0", features = ["derive"] }
rand = "0.8.4"
walkdir = "2.3.2"
